### ISSUE TITLE
Newest zen browser update 1.0.1-a.18 breaks theming.

### ISSUE THREAD

**Issue by undefinedcode0** [catppuccin/zen-browser#11]
Immediately after updating Zen, I noticed some elements not being themed (*as far as I know*) like the compact toolbar background, and correct me if I'm wrong, the browser background. Here are your Theme Changes that you should look out for and fix.

* Compact mode will now use '**--zen-main-browser-background-toolbar**' as the background color 
* Browser background isn't defined on **zen-main-app-wrapper** element anymore but on the **#browser** element
* Added a new variable for the translucency of the browser in macos"

**Comment by undefinedcode0** [comment]
![image](https://github.com/user-attachments/assets/32dc4481-d01c-4a32-93ba-eb13980fcf36)

**Comment by undefinedcode0** [comment]
![image](https://github.com/user-attachments/assets/8d27f52a-ee69-4f7d-9981-0fe98a9a4110)

**Comment by IAmJafeth** [comment]
Hi @undefinedcode0,

I new something like this would happen when Mauro talked about this changes.

I am planing to review and asses this once I have some bandwidth.

Thanks for the report!

**Comment by undefinedcode0** [comment]
Youre welcome, man! I'll be looking forward to the fix, I'll be waiting patiently!  👍

**Comment by IAmJafeth** [comment]
Hey @undefinedcode0,

I was checking this and I can see that the Catppuccin Theme was not affected by the update.
It seems the variables I was using were not affected by this change.

The only thing that I can see that got 'broken' was the border around the Viewport, however this  was an intentional change in this new Zen UI which deprecated it.

Adding `--zen-main-browser-background-toolbar` to has no effect, as this background was already themed using: 
```css
  #TabsToolbar {
        background-color: #181825 !important;
    }
```
And for the browser background `--zen-themed-toolbar-bg` along with `--zen-colors-tertiary` seems to be working just fine.

This theme is designed to be OS agnostic, therefore, it is not planned to support translucency for MacOS, this can be added by the user if wanted.

Let me know if I am not taking something in consideration, we can always reopen the issue if needed

**Comment by undefinedcode0** [comment]
I forgot to mention that the Theme Changes were from the release notes. But, is there a way to theme the viewport again?

**Comment by IAmJafeth** [comment]
There most be a way tinkering with the CSS to bring the border back, however it is Catppuccin's philosophy to be a color scheme that does not modify the default behavior of the application.

So if Zen decided to go with this UI, the Catppuccin theme will not modify it.

**Comment by undefinedcode0** [comment]
Interesting... Thanks for acknowledging my issue though. I was wondering if there was a fix, but for now, there isn't.
